// Copyright (c) Thanh Tu. All rights reserved.
// Licensed under the MIT License.

using System.CommandLine;
using System.Text.Json;
using EtabExtension.CLI.Features.ExtractResults.Models;
using EtabExtension.CLI.Shared.Common;
using EtabExtension.CLI.Shared.Infrastructure.Etabs.Unit;
using Microsoft.Extensions.DependencyInjection;

namespace EtabExtension.CLI.Features.ExtractResults;

public static class ExtractResultsCommand
{
    public static Command Create(IServiceProvider services)
    {
        var command = new Command(
            "extract-results",
            "Extract ETABS analysis results tables to .parquet files via a hidden ETABS instance");

        var fileOption = new Option<string>("--file")
        {
            Description = "Path to the .edb file",
            Required = true
        };
        fileOption.Aliases.Add("-f");

        var outputDirOption = new Option<string>("--output-dir")
        {
            Description = "Directory to write all .parquet files into",
            Required = true
        };
        outputDirOption.Aliases.Add("-o");

        // Rust serialises an ExtractResultsRequest subset to JSON and passes it here.
        // filePath and outputDir are supplied as separate flags above (not inside JSON)
        // so Rust can construct them from its own path logic without re-embedding them.
        //
        // The JSON supports an optional "units" field alongside "tables":
        //   --request '{"units":"SI_kN_m","tables":{"baseReactions":{"loadCases":["*"]}}}'
        //   --request '{"tables":{"storyDefinitions":{}}}'   ← units defaults to US_Kip_Ft
        var requestJsonOption = new Option<string>("--request")
        {
            Description =
                "JSON with optional 'units' and required 'tables' (TableSelections + per-table filters). " +
                $"units defaults to {EtabsUnitPreset.Default} when omitted. " +
                "Generated by the Rust CLI from the Excel config file.",
            Required = true
        };
        requestJsonOption.Aliases.Add("-r");

        command.Options.Add(fileOption);
        command.Options.Add(outputDirOption);
        command.Options.Add(requestJsonOption);

        command.SetAction(async parseResult =>
        {
            var filePath = parseResult.GetValue(fileOption)!;
            var outputDir = parseResult.GetValue(outputDirOption)!;
            var requestJson = parseResult.GetValue(requestJsonOption)!;

            // ── Deserialise ───────────────────────────────────────────────────
            ExtractResultsRequest? partialRequest;
            try
            {
                partialRequest = JsonSerializer.Deserialize<ExtractResultsRequest>(
                    requestJson,
                    new JsonSerializerOptions { PropertyNameCaseInsensitive = true });
            }
            catch (JsonException ex)
            {
                var fail = Result.Fail<ExtractResultsData>($"Invalid --request JSON: {ex.Message}");
                Environment.Exit(fail.ExitWithResult());
                return;
            }

            if (partialRequest is null)
            {
                var fail = Result.Fail<ExtractResultsData>("--request JSON deserialised to null");
                Environment.Exit(fail.ExitWithResult());
                return;
            }

            // Validate units before starting ETABS — fast failure with a clear message
            var (_, unitsError) = EtabsUnitPreset.Resolve(partialRequest.Units);
            if (unitsError is not null)
            {
                var fail = Result.Fail<ExtractResultsData>(unitsError);
                Environment.Exit(fail.ExitWithResult());
                return;
            }

            // Merge CLI flags into the deserialised request
            var request = partialRequest with
            {
                FilePath = filePath,
                OutputDir = outputDir,
            };

            var service = services.GetRequiredService<IExtractResultsService>();
            var result = await service.ExtractAsync(request);
            Environment.Exit(result.ExitWithResult());
        });

        return command;
    }
}
