// Copyright (c) Thanh Tu. All rights reserved.
// Licensed under the MIT License.

using System.CommandLine;
using System.Text.Json;
using EtabExtension.CLI.Features.ExtractResults.Models;
using EtabExtension.CLI.Shared.Common;
using Microsoft.Extensions.DependencyInjection;

namespace EtabExtension.CLI.Features.ExtractResults;

public static class ExtractResultsCommand
{
    public static Command Create(IServiceProvider services)
    {
        var command = new Command(
            "extract-results",
            "Extract ETABS analysis results tables to .parquet files via a hidden ETABS instance");

        // ── Required: the .edb to open ────────────────────────────────────────
        var fileOption = new Option<string>("--file")
        {
            Description = "Path to the .edb file",
            Required = true
        };
        fileOption.Aliases.Add("-f");

        // ── Required: where to write all .parquet files ───────────────────────
        var outputDirOption = new Option<string>("--output-dir")
        {
            Description = "Directory to write all .parquet files into",
            Required = true
        };
        outputDirOption.Aliases.Add("-o");

        // ── Required: the full request JSON ──────────────────────────────────
        // Rust serialises an ExtractResultsRequest to JSON and passes it here.
        // This keeps the CLI surface stable — all table-specific filter logic
        // stays in Rust (reads from Excel) and is forwarded verbatim to C#.
        //
        // Example:
        //   --request '{"tables":{"baseReactions":{"loadCases":["DEAD","LIVE","EQX"]},"storyForces":{"loadCases":["DEAD","LIVE","EQX"]},"jointDrifts":{"loadCases":["EQX","EQY"],"groups":["DriftJoints"]}}}'
        var requestJsonOption = new Option<string>("--request")
        {
            Description =
                "Full ExtractResultsRequest JSON (TableSelections + per-table filters). " +
                "Generated by the Rust CLI from the Excel config file.",
            Required = true
        };
        requestJsonOption.Aliases.Add("-r");

        command.Options.Add(fileOption);
        command.Options.Add(outputDirOption);
        command.Options.Add(requestJsonOption);

        command.SetAction(async parseResult =>
        {
            var filePath = parseResult.GetValue(fileOption)!;
            var outputDir = parseResult.GetValue(outputDirOption)!;
            var requestJson = parseResult.GetValue(requestJsonOption)!;

            // ── Deserialise the TableSelections from Rust ─────────────────────
            TableSelections? tables;
            try
            {
                tables = JsonSerializer.Deserialize<TableSelections>(requestJson,
                    new JsonSerializerOptions { PropertyNameCaseInsensitive = true });
            }
            catch (JsonException ex)
            {
                var fail = Result.Fail<ExtractResultsData>(
                    $"Invalid --request JSON: {ex.Message}");
                Environment.Exit(fail.ExitWithResult());
                return;
            }

            if (tables is null)
            {
                var fail = Result.Fail<ExtractResultsData>(
                    "--request JSON deserialised to null");
                Environment.Exit(fail.ExitWithResult());
                return;
            }

            var request = new ExtractResultsRequest
            {
                FilePath = filePath,
                OutputDir = outputDir,
                Tables = tables
            };

            var service = services.GetRequiredService<IExtractResultsService>();
            var result = await service.ExtractAsync(request);

            Environment.Exit(result.ExitWithResult());
        });

        return command;
    }
}
